export default{
    
    nowUp: ['gentryOfHermitage2','theHeronsCourt','tapestryOfGoldenFlames','geTanNightmare'],

    defaultResult: {
        star5: [
            '5-Keqing-electric',
            '5-Qiqi-ice',
            '5-Mona-water',
            '5-Diluc-fire',
            '5-Jean-wind',
        ],
        star4: [
            '4-YunJin-stone',
            '4-Gorou-stone',
            '4-Thoma-fire',
            '4-Sara-electric',
            '4-Sayu-wind',
            '4-Yanfei-fire',
            '4-Rosaria-ice',
            '4-Xinyan-fire',
            '4-Diona-ice',
            '4-Sucrose-wind',
            '4-Chongyun-ice',
            '4-Noelle-stone',
            '4-Bennett-fire',
            '4-Fischl-electric',
            '4-Ningguang-stone',
            '4-Xingqiu-water',
            '4-Beidou-electric',
            '4-Xiangling-fire',
            '4-Razor-electric',
            '4-Barbara-water',
            
            '4-Favonius_Sword-sword',
            '4-The_Flute-sword',
            '4-Sacrificial_Sword-sword',
            '4-Lion\'s_Roar-sword',
            '4-Favonius_Greatsword-claymore',
            '4-The_Bell-claymore',
            '4-Sacrificial_Greatsword-claymore',
            '4-Rainslasher-claymore',
            '4-Dragon\'s_Bane-pike',
            '4-Favonius_Lance-pike',
            '4-Favonius_Codex-pike',
            '4-The_Widsith-magic',
            '4-Sacrificial_Fragments-magic',
            '4-Mappa_Mare-magic',
            '4-Eye_of_Perception-magic',
            '4-Favonius_Warbow-bow',
            '4-The_Stringless-bow',
            '4-Sacrificial_Bow-bow',
            '4-Rust-bow',
            '4-Mouun\'s_Moon-bow'
        ],
        star3: [
            '3-Cool_Steel-sword',
            '3-Harbinger_of_Dawn-sword',
            '3-Traveler\'s_Handy_Sword-sword',
            '3-Fillet_Blade-sword',
            '3-Skyrider_Sword-sword',
            '3-Ferrous_Shadow-sword',
            '3-Bloodtainted_Greatsword-claymore',
            '3-White_Iron_Greatsword-claymore',
            '3-Debate_Club-claymore',
            '3-Skyrider_Greatsword-claymore',
            '3-White_Tassel-pike',
            '3-Halberd-pike',
            '3-Black_Tassel-pike',
            '3-Magic_Guide-magic',
            '3-Thrilling_Tales_of_Dragon_Slayers-magic',
            '3-Otherworldly_Story-magic',
            '3-Emerald_Orb-magic',
            '3-Twin_Nephrite-magic',
            '3-Raven_Bow-bow',
            '3-Sharpshooter\'s_Oath-bow',
            '3-Recurve_Bow-bow',
            '3-Slingshot-bow',
            '3-Messenger-bow'
        ]
    }
}