export default{
    
    nowUp: ['gentryOfHermitage2','theHeronsCourt'],

    defaultResult: {
        star5: [
            '5-Keqing',
            '5-Qiqi',
            '5-Mona',
            '5-Diluc',
            '5-Jean',
            '5-Aquaila Favonia',
            '5-Skyward-Blade',
            '5-Skyward-Pride',
            '5-Skyward-Spine',
            '5-Skyward-Atlas',
            '5-Skyward-Harp',
            '5-Wolf\'s Gravestone',
            '5-Amos\'s Bow',
            '5-Primordial Jade Winged-Spear'
        ],
        star4: [
            '4-YunJin',
            '4-Gorou',
            '4-Thoma',
            '4-Sara',
            '4-Sayu',
            '4-Yanfei',
            '4-Rosaria',
            '4-Xinyan',
            '4-Diona',
            '4-Sucrose',
            '4-Chongyun',
            '4-Noelle',
            '4-Bennett',
            '4-Fischl',
            '4-Ningguang',
            '4-Xingqiu',
            '4-Beidou',
            '4-Xiangling',
            '4-Razor',
            '4-Barbara'
        ],
        star4Weapon: [
            '4-Favonius-Sword',
            '4-The-Flute',
            '4-Sacriificial-Sword',
            '4-Lion\'s-Roar',
            '4-Favonius-Greatsword',
            '4-The-Bell',
            '4-Sacrificial-Greatsword',
            '4-Rainslasher',
            '4-Dragon\'s-Bane',
            '4-Favonius-Lance',
            '4-Favonius-Codex',
            '4-The-Widsith',
            '4-Sacrificial-Fragments',
            '4-Mappa-Mare',
            '4-Eye-of Perception',
            '4-Favonius-Warbow',
            '4-The-Stringless',
            '4-Sacrificial-Bow',
            '4-Rust',
            '4-Mouun\'s-Moon'
        ],
        star3: [
            '3-Cool-Steel',
            '3-Harbinger-of Dawn',
            '3-Traveler\'s-Handy-Sword',
            '3-Fillet-Blade',
            '3-Skyrider-Sword',
            '3-Ferrous-Shadow',
            '3-Bloodtainted-Greatsword',
            '3-White Iron-Greatsword',
            '3-Debate-Club',
            '3-Skyrider-Greatsword',
            '3-White-Tassel',
            '3-Halberd',
            '3-Black-Tassel',
            '3-Magic-Guide',
            '3-Thrilling-Tables-if-Dragon',
            '3-Otherwirldly-Story',
            '3-Emerald-Orb',
            '3-Twin-Nephrite',
            '3-Raven-Bow',
            '3-Sharpshooter\'s-Oath',
            '3-Recurve-Bow',
            '3-Slingshot',
            '3-Messenger'
        ]
    }
}